---
hostname: devbox
memory: 1024
cpus: 2
ip: 172.16.16.16

folders:
  - map: ~/dev/projects
    to: /home/vagrant/dev

apps:
  - type: rails
    name: Hello World
    server_name: hello.app
    app_path: /home/vagrant/dev/hello
    database:
      type: postgres
      name: hellodb
      user: hellodb_user
      password: hola

mysql_admin_passwords:
  root: t00r
  dba: n1mda

ports:
  - host: 30080
    guest: 80
  - host: 30443
    guest: 443
  - host: 33000
    guest: 3000
  - host: 33060
    guest: 3306
  - host: 30022
    guest: 22
    id: ssh

authorize: ~/.ssh/id_rsa.pub
keys:
  - ~/.ssh/id_rsa
