---
hostname: devbox
memory: 1024
cpus: 2
ip: 172.16.16.16

folders:
  - map: ~/dev/projects
    to: /home/ubuntu/dev

apps:
  - type: laravel
    server_name: hello-laravel.app
    app_path: /home/ubuntu/dev/hello-laravel
    install_dependencies:
      composer: true
      npm: true
      bower: true
      grunt: true
      gulp: true
    database:
      type: mysql
      name: hellolardb
      user: hellolardb_user
      password: hola
      migrate: true
  - type: rails
    name: Hello Rails
    server_name: hello-rails.app
    app_path: /home/ubuntu/dev/hello-rails
    database:
      type: postgres
      name: hellorlsdb
      user: hellorlsdb_user
      password: hola

mysql_admin_passwords:
  root: t00r
  dba: n1mda

ports:
  - host: 30080
    guest: 80
  - host: 30443
    guest: 443
  - host: 33000
    guest: 3000
  - host: 33306
    guest: 3306
  - host: 30022
    guest: 22
    id: ssh

authorize: ~/.ssh/id_rsa.pub
keys:
  - ~/.ssh/id_rsa
