---
- shell: hostname
  register: current_hostname

- name: Install mysql packages
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-pip
    - python-dev
    - python-mysqldb

- name: Install required python modules
  pip: name=mysql-python

- name: Enable and start mysql
  service: name=mysql enabled=yes state=started

- name: Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql_root_password }} login_user=root login_password={{ mysql_root_password }}
  with_items:
    - '{{ current_hostname.stdout | lower }}'
    - 127.0.0.1
    - ::1
    - localhost

- name: Create dba account for external access
  mysql_user: name=dba host='%' password={{ mysql_dba_password }} priv=*.*:ALL state=present login_user=root login_password={{ mysql_root_password }}

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql_root_password }}
  with_items:
    - localhost
    - '{{ current_hostname.stdout | lower }}'

- name: Ensure mysql listens on all interfaces
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf
              regexp='bind-address\s*=\s*127\.0\.0\.1\s*'
              line='bind-address = 0.0.0.0'
              state=present
              backrefs=yes

- name: Restart mysql
  service: name=mysql enabled=yes state=restarted
