---
server:
  timezone: America/New_York
  locale: en_US.UTF-8
  extra_packages: [imagemagick,libgmp-dev]

ssl_cert:
  country: US
  state: Florida
  city: Miami
  organization: DevOrg

vagrant_user: ubuntu

nginx:
  ssl_cert_path: /etc/nginx/ssl

pgsql:
  distro: xenial

rails:
  env: development
  sockets_path: /var/sockets
