---
server:
  timezone: America/New_York
  locale: en_US.UTF-8
  extra_packages: [imagemagick]

ssl_cert:
  country: US
  state: Florida
  city: Miami
  organization: DevOrg

vagrant_user: vagrant

nginx:
  ssl_cert_path: /etc/nginx/ssl

php:
  ppa: php5-5.6

pgsql:
  distro: trusty

rails:
  env: development
  sockets_path: /var/sockets
