---
- name: Set permissions on socket - owner
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = {{ vagrant_user }}'"

- name: Set permissions on socket - group
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.group' line='listen.group = {{ vagrant_user }}'"

- name: Set permissions on socket - mode
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0666'"

- name: Set user for processes
  replace: "dest=/etc/php5/fpm/pool.d/www.conf regexp='www-data' replace='{{ vagrant_user }}'"

- name: ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'

- name: restart php5-fpm
  service: name=php5-fpm enabled=yes state=restarted
