---
- name: Ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'
              state=present
              backrefs=yes

- name: Enable opcache cli
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=1'
              state=present
              backrefs=yes
