---
- name: Install Nginx
  apt: pkg=nginx state=latest

- name: Create config file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Create ssl certificate directory
  file: path={{ nginx.ssl_cert_path }} recurse=yes state=directory
