---

- hosts: all
  gather_facts: no
  become: true

  pre_tasks:
    - name: Install python 2
      raw: sh -c '[ -f /usr/bin/python ] || sudo apt-get -y install python-simplejson'

  vars_files:
    - vars/settings.yml

  roles:
    - vagrant_host
    - server
    - nginx
    - mysql
    - postgres
    - redis
    - php
    - composer
    - rails
    - node
    - apps
