---
- name: Set the hostname in /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: Remove hostname mapping from /etc/hosts
  lineinfile: dest=/etc/hosts state=absent regexp='^127\.0\.0\.1\s+{{ hostname }}'

- name: Add hostname to localhost mapping in /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 {{ hostname }} localhost' owner=root group=root mode=0644
